-- ============================================================
-- WifakBank Dashboard Client - Initial Schema
-- ============================================================

-- Audit log table to track SSO logins
CREATE TABLE SSO_ACCESS_LOG (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR2(100)  NOT NULL,
    ACCESS_TIME     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(500),
    TOKEN_ISSUED_AT TIMESTAMP,
    TOKEN_EXPIRES_AT TIMESTAMP,
    STATUS          VARCHAR2(20)   DEFAULT 'SUCCESS' NOT NULL
);

-- Index for faster username lookups
CREATE INDEX IDX_SSO_LOG_USERNAME ON SSO_ACCESS_LOG(USERNAME);
CREATE INDEX IDX_SSO_LOG_ACCESS_TIME ON SSO_ACCESS_LOG(ACCESS_TIME);
