-- ============================================================
-- Dashboard Client - Local Users for standalone login
-- ============================================================
-- This migration is written defensively:
-- DROP is attempted first so a re-run after a partial failure is safe.
-- ============================================================

-- Drop USERS table if it exists from a previous partial run
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF; -- -942 = table does not exist
END;
/

-- Drop index if it exists
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_USERS_USERNAME';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN RAISE; END IF; -- -1418 = index does not exist
END;
/

-- Create USERS table
CREATE TABLE USERS (
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME      VARCHAR2(100)  NOT NULL,
    PASSWORD_HASH VARCHAR2(255)  NOT NULL,
    FULL_NAME     VARCHAR2(200),
    EMAIL         VARCHAR2(200),
    ROLE          VARCHAR2(50)   DEFAULT 'USER' NOT NULL,
    ACTIVE        NUMBER(1)      DEFAULT 1 NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);

-- Test user: username=test  password=test123  (BCrypt $2a$10$ hash)
INSERT INTO USERS (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, ROLE)
VALUES (
    'test',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    'Test User',
    'test@wifakbank.com',
    'USER'
);

COMMIT;
