spring.application.name=WifakBankProject

# Oracle DataSource
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=C##wifak_platform
spring.datasource.password=wifak123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# Run data.sql AFTER Hibernate has created/updated tables
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

# Server encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Embedded LDAP
spring.ldap.embedded.base-dn=dc=wifakbank,dc=tn
spring.ldap.embedded.ldif=classpath:test-users.ldif
spring.ldap.embedded.port=8389

# AD / LDAP connection (not used in dev profile)
app.ad.domain=wifakbank.tn
app.ad.url=ldap://localhost:389/

# JWT (use a strong secret in production!)
app.jwt.secret=wifakbank-jwt-secret-key-for-testing-purposes-only-change-in-production
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Server
server.port=8080

# Mail / SMTP (mock for dev)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
