-- =============================================================================
-- Seed data – Oracle-compatible with FROM DUAL
-- =============================================================================

-- ── DEPARTMENTS ──────────────────────────────────────────────────────────────
INSERT INTO DEPARTMENTS (ID, CODE, NAME, DESCRIPTION)
SELECT 1, 'IT', 'Informatique', 'Département informatique' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE CODE = 'IT');

INSERT INTO DEPARTMENTS (ID, CODE, NAME, DESCRIPTION)
SELECT 2, 'RH', 'Ressources Humaines', 'Département RH' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE CODE = 'RH');

INSERT INTO DEPARTMENTS (ID, CODE, NAME, DESCRIPTION)
SELECT 3, 'FINANCE', 'Finance', 'Département finance' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE CODE = 'FINANCE');

INSERT INTO DEPARTMENTS (ID, CODE, NAME, DESCRIPTION)
SELECT 4, 'COMMERCIAL', 'Commercial', 'Département commercial' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE CODE = 'COMMERCIAL');

-- ── APPLICATIONS ─────────────────────────────────────────────────────────────
INSERT INTO APPLICATIONS (ID, CODE, NOM, DESCRIPTION, URL, ICON, AUTH_TYPE, STATUS)
SELECT 1, 'DOI', 'Dématérialisation', 'Gestion documentaire dématérialisée', 'http://doi.wifakbank.tn', 'description', 'AD', 'ACTIVE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APPLICATIONS WHERE CODE = 'DOI');

INSERT INTO APPLICATIONS (ID, CODE, NOM, DESCRIPTION, URL, ICON, AUTH_TYPE, STATUS)
SELECT 2, 'GED', 'GED', 'Gestion électronique des documents', 'http://ged.wifakbank.tn', 'folder', 'AD', 'ACTIVE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APPLICATIONS WHERE CODE = 'GED');

INSERT INTO APPLICATIONS (ID, CODE, NOM, DESCRIPTION, URL, ICON, AUTH_TYPE, STATUS)
SELECT 3, 'CRM', 'CRM', 'Gestion de la relation client', 'http://crm.wifakbank.tn', 'people', 'AD', 'ACTIVE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APPLICATIONS WHERE CODE = 'CRM');

INSERT INTO APPLICATIONS (ID, CODE, NOM, DESCRIPTION, URL, ICON, AUTH_TYPE, STATUS)
SELECT 4, 'CREDIT', 'Crédit', 'Gestion des dossiers de crédit', 'http://credit.wifakbank.tn', 'account_balance', 'AD', 'ACTIVE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APPLICATIONS WHERE CODE = 'CREDIT');

INSERT INTO APPLICATIONS (ID, CODE, NOM, DESCRIPTION, URL, ICON, AUTH_TYPE, STATUS)
SELECT 5, 'RH', 'Ressources Humaines', 'Gestion du personnel', 'http://rh.wifakbank.tn', 'badge', 'AD', 'ACTIVE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM APPLICATIONS WHERE CODE = 'RH');

-- ── ROLES ────────────────────────────────────────────────────────────────────
INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 1, 'Administrateur DOI', 'Accès complet DOI' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 1);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 2, 'Consultation DOI', 'Lecture seule DOI' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 2);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 3, 'Administrateur GED', 'Accès complet GED' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 3);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 4, 'Consultation GED', 'Lecture seule GED' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 4);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 5, 'Administrateur CRM', 'Accès complet CRM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 5);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 6, 'Consultation CRM', 'Lecture seule CRM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 6);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 7, 'Administrateur CREDIT', 'Accès complet Crédit' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 7);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 8, 'Validation CREDIT', 'Validation des dossiers Crédit' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 8);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 9, 'Consultation CREDIT', 'Lecture seule Crédit' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 9);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 10, 'Responsable RH', 'Gestion complète RH' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 10);

INSERT INTO ROLES (ID, NOM, DESCRIPTION)
SELECT 11, 'Consultation RH', 'Lecture seule RH' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ID = 11);

-- ── USERS ──────────────────────────────────────────────────────────────────
INSERT INTO USERS (ID, LOGIN, NOM, PRENOM, EMAIL, AUTH_TYPE, STATUS, CREATED_AT, DEPARTMENT_ID)
SELECT 1, 'admin', 'Admin', 'Système', 'admin@wifakbank.tn', 'AD', 'ACTIVE', CURRENT_TIMESTAMP, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE LOGIN = 'admin');

INSERT INTO USERS (ID, LOGIN, NOM, PRENOM, EMAIL, AUTH_TYPE, STATUS, CREATED_AT, DEPARTMENT_ID)
SELECT 2, 'ahmed', 'Ben Ali', 'Ahmed', 'ahmed@wifakbank.tn', 'AD', 'ACTIVE', CURRENT_TIMESTAMP, 3 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE LOGIN = 'ahmed');

-- ── USER_ROLES ─────────────────────────────────────────────────────────────
INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 1, 2, 8 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 2 AND ROLE_ID = 8);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 2, 2, 11 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 2 AND ROLE_ID = 11);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 3, 2, 3 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 2 AND ROLE_ID = 3);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 4, 1, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 1 AND ROLE_ID = 1);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 5, 1, 3 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 1 AND ROLE_ID = 3);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 6, 1, 5 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 1 AND ROLE_ID = 5);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 7, 1, 7 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 1 AND ROLE_ID = 7);

INSERT INTO USER_ROLES (ID, USER_ID, ROLE_ID)
SELECT 8, 1, 10 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USER_ROLES WHERE USER_ID = 1 AND ROLE_ID = 10);